import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google';
import "./globals.css";

import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Items CRUD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 2. Add your Header here */}
        <Header />

        {/* We wrap 'children' in a 'main' tag for semantics
          and to add some consistent padding. 
        */}
        <main style={{ minHeight: '80vh', padding: '0 1rem', maxWidth: '1100px', margin: '2rem auto' }}>
          {children} {/* 'children' is where your page.tsx will be rendered */}
        </main>
        
        {/* 3. Add your Footer here */}
        <Footer />
      </body>
    </html>
  );
}
